version: '3.8'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - '3001:3000'
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      HASH_SALT: your-hash-salt-here-change-this-in-production
      DATABASE_TYPE: postgresql
    depends_on:
      - db
    restart: unless-stopped
    profiles:
      - analytics

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - analytics

volumes:
  umami-db:
